/*
new cursoreffects.fairyDustCursor({ element: document.querySelector("#fairyDust") })
new cursoreffects.ghostCursor({ element: document.querySelector("#ghost") })
new cursoreffects.followingDotCursor({ element: document.querySelector("#following") })
new cursoreffects.emojiCursor({ element: document.querySelector("#emoji") })
new cursoreffects.snowflakeCursor({ element: document.querySelector("#snowflake") })
new cursoreffects.characterCursor({ element: document.querySelector("#character") })
new cursoreffects.clockCursor({ element: document.querySelector("#clock") })
new cursoreffects.textFlag({ element: document.querySelector("#textFlag"), text: 'Like & Subscribe' })
*/
new cursoreffects.Trailing({ element: document.querySelector("#trailing")})
new cursoreffects.SpringyEmoji({ element: document.querySelector("#springs")})
new cursoreffects.Rainbow({ element: document.querySelector("#rainbow")})
new cursoreffects.Bubble({ element: document.querySelector("#bubbles") })
new cursoreffects.Dragon({ element: document.querySelector("#dragon") })